version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/gookit/color
    versions:
    - 1.3.6
    - 1.3.7
  - dependency-name: github.com/google/uuid
    versions:
    - 1.2.0
  - dependency-name: github.com/go-errors/errors
    versions:
    - 1.1.1
  - dependency-name: github.com/unrolled/secure
    versions:
    - 1.0.8
  - dependency-name: github.com/gin-gonic/gin
    versions:
    - 1.6.3
