name: Deploy server
on:
  push:
    branches: [ main ]
jobs:
  deploy-server:
    name: Deploy server
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18 ]
        go-version: [ 1.18 ]
    steps:
    - name: Checkout repository
      id: checkout-repository
      uses: actions/checkout@v3
    - name: Install Node ${{ matrix.node-version }}
      id: install-node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install node modules
      id: install-node-modules
      uses: bahmutov/npm-install@v1
      with:
        working-directory: ui
    - name: Build UI
      id: build-ui
      run: npm --prefix ui run build
    - name: Cache go modules
      id: cache-go-modules
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-
    - name: Install Go ${{ matrix.go-version }}
      id: install-go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Download go modules
      id: download-gomodules
      run: go mod download
    - name: Build server
      id: build-server
      run: go build -o build/server ./cmd/server
    - name: Build container image
      id: build-container-image
      run: docker build -t registry.digitalocean.com/rdnt/myst:$(echo $GITHUB_SHA | head -c7) -t registry.digitalocean.com/rdnt/myst:latest .
    - name: Install doctl
      id: install-doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      id: registry-login
      run: doctl registry login --expiry-seconds 600
    - name: Push image
      id: push-image
      run: docker push registry.digitalocean.com/rdnt/myst:$(echo $GITHUB_SHA | head -c7) && docker push registry.digitalocean.com/rdnt/myst:latest
    - name: Create application deployment
      id: create-deployment
      run: doctl apps create-deployment ${{ secrets.DIGITALOCEAN_APP_ID }}
