name: go
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.14]
    steps:
    - name: Set up Go ${{ matrix.go-version }}
      id: setup-go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Check out code into the Go module directory
      id: checkout
      uses: actions/checkout@v2
    - name: Get dependencies
      id: get-dependencies
      run: |
        go get -v -t -d ./go/...
    - name: Build
      id: build
      run: go build -o main -v ./go
