name: go
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.16]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go ${{ matrix.go-version }}
      id: setup-go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Get dependencies
      id: get-dependencies
      run: go get -v -t -d ./cmd/server/...
    - name: Build
      id: build
      run: go build ./cmd/server/main.go
    - name: Test
      id: test
      run: go test -test.v ./cmd/server
