name: go
on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened, edited ]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 1.16 ]
    steps:
      - name: Checkout source code
        id: checkout
        uses: actions/checkout@v2
      - name: Cache go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - name: Set up Go ${{ matrix.go-version }}
        id: setup-go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Download go modules
        id: get-modules
        run: go mod download
      - name: Build server
        id: build
        run: go build ./cmd/server/main.go
      - name: Test server
        id: test
        run: go test -test.v ./cmd/server
