name: ui
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16, 17, 18 ]
    steps:

    - name: Checkout code
      id: checkout-code
      uses: actions/checkout@v2

    - name: Install Node ${{ matrix.node-version }}
      id: install-node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install node modules
      id: install-node-modules
      uses: bahmutov/npm-install@v1
      with:
        working-directory: ui

    - name: Build UI
      id: build-ui
      run: npm --prefix ui run build
